### PR TITLE
Commit master from downstream.

### PR DESCRIPTION
**Pull request by dfederlein**
Signed-off-by: David Federlein <davidf@mindpointgroup.com>

### CODE REVIEW

**Comment by Michael-Angel-Sec** [comment]
@jamescassell Anything I can do to help on this PR?

**Comment by jamescassell** [comment]
I'll need to make some time to go thru it, but probably won't be for at least a couple of weeks... some of these changes are undo's of PRs that were merged here "upstream" that didn't make their way to the "downstream" paid product.

**Comment by dfederlein** [comment]
Likely there's more to change: we're actively rewriting this role in line with our new verification tools (those will be up on this GH org's repos soon).

**Comment by georgenalen** [comment]
Hello,
 We are closing this PR since we (folks at MindPoint Group) have a significant update to the role and want to start with a clean slate both PR's and issues. Please continue to use the role and create PR's

-George

**Pull request closed without merging**
