### PR TITLE
V3R14 to main release

### PR DESCRIPTION
**Pull request by uk-bolly**
**Overall Review of Changes:**
- Audit updated
  - moved audit into prelim
  - updates to audit logic for copy and archive options

- RHEL-07-020019 - title and ruleid update
- RHEL-07-020022 - ruleid update
- RHEL-07-020210 - ruleid update
- RHEL-07-020220 - ruleid update
- RHEL-07-020100 - ruleid update and bin/false
- RHEL-07-020101 - ruleid update and bin/false
- RHEL-07-040180 - ruleid update and bin/false
- RHEL-07-040190 - ruleid update and bin/false

**Issue Fixes:**
Pre-commits

**Enhancements:**
Audit updates X86_64 and ARM64
Pipeline updates
General improvements
jmespath removal
Rebase carried out due to historical issues

**How has this been tested?:**
Manually and Pipeline

### CODE REVIEW

**Comment by uk-bolly** [comment]
pipeline failure expected due to new pipeline config
see manually run on new pipeline with a manual run
https://github.com/ansible-lockdown/RHEL7-STIG/actions/runs/11577296930

**Review by MrSteve81 — DISMISSED** [review]
A nice large Update.  Well done!

**Review by georgenalen — APPROVED** [review]
Looks good!

**Comment by uk-bolly** [comment]
Main pipeline expected to fail as moved to new workflow

**Pull request merged**
